### ISSUE TITLE
How to properly delete locale files or some parts?

### ISSUE THREAD

**Issue by ZwerOxotnik** [dima74/factorio-mods-localization#10]
I tried to delete some .cfg files, but I encountered some problems. Files in locale/en/\*.cfg were successfully deleted, however, other files in other folders were "restored" by [https://github.com/dima74/factorio-mods-localization](https://github.com/dima74/factorio-mods-localization)

Some of my mods have unnecessary/outdated parts in .cfg files and I'm not sure how to remove them with https://github.com/dima74/factorio-mods-localization

**Comment by dima74** [comment]
@ZwerOxotnik sorry for long response. These situations should be handled automatically in the future (#7), but for now I can manually delete necessary files from Crowdin. Could you please provide which files should be deleted

**Comment by dima74** [comment]
This should work now, see #7 for details
