### ISSUE TITLE
Disappeared part of localization

### ISSUE THREAD

**Issue by ZwerOxotnik** [dima74/factorio-mods-localization#11]
ZwerOxotnik/diplomacy@d95b51b it seems wrong

**Comment by dima74** [comment]
I think this is bug in Crowdin - when [some section is removed](https://github.com/ZwerOxotnik/diplomacy/commit/43f947c236c8246cb13a7faa826c4294e9ba09d7#diff-7fc306da33fdb77621cbc2229ff6b81ebeff50d0febae065731f2194384f9918L30), all translations for strings in this section are lost. I reported it to Crowdin. Feel free to reopen if you find any other problems.
