### ISSUE TITLE
The project isn't available on Crowdin

### ISSUE THREAD

**Issue by ZwerOxotnik** [dima74/factorio-mods-localization#13]
I can't translate on Crowdin, "The project you are trying to translate is currently suspended".

@dima74

**Comment by dima74** [comment]
Yeah, thanks, we have exceeded the free plan. I submitted request to Crowdin for the open-source license for our project.

**Comment by ZwerOxotnik** [comment]
If I remove integration from some mod, will be the project available for some time more? (I assume, yes)

**Comment by dima74** [comment]
Crowdin team has extended our project limits, so the project should be again available now

> If I remove integration from some mod, will be the project available for some time more? (I assume, yes)

It would require manual deletion of files from Crowdin because of #7, so it is better not to do this
