### ISSUE TITLE
Branch Protection Rules

### ISSUE THREAD

**Issue by AndrewWeinmann** [dima74/factorio-mods-localization#14]
How does this work if the main branch of a mod has a branch protection rule set up requiring pull requests?

**Comment by dima74** [comment]
Hi @Porkchop13! Unfortunatelly it is not supported now

**Comment by AndrewWeinmann** [comment]
Ok, thanks for the clarification and quick reply!

**Comment by dima74** [comment]
Hi @Porkchop13! I recently added support for case when main branch has protection rules - now pull request will be created. ~~Note that this requires new "pull requests" permission for the app (github should send email about it I guess)~~. Update: pull request will be created from fork, additional permission is not required. Thanks!

**Comment by dima74** [comment]
If you find any problems please let me know
