### ISSUE TITLE
[Question] When are selected Repositories available on Crowdin?

### ISSUE THREAD

**Issue by Xman1109** [dima74/factorio-mods-localization#15]
2 Days ago I selected 3 of my repositories (Atomic Overhaul, More Ammo, More Repair Packs) to be translated on Crowdin, And only 1/3 (More Repair Packs) is currently on Crowdin, so I am wondering where the other 2 are. Sorry if I am just impatient.

Btw, cool project and Greetings from Germany!

**Comment by dima74** [comment]
Hi @Xman1109! They should be added instantly but looks like there was some error during import. Currently files in any localization folder (such as `/locale/de`) must have same names as files in `/locale/en` folder for correct work. Could you please do the renaming and then uninstall github app and install again? E.g. rename both [`Deutsch.cfg`](https://github.com/Xman1109/Atomic_Overhaul/blob/main/locale/de/Deutsch.cfg) and [`English.cfg`](https://github.com/Xman1109/Atomic_Overhaul/blob/main/locale/en/English.cfg) to `base.cfg`, etc

**Comment by Xman1109** [comment]
![Screenshot_20220730_170127](https://user-images.githubusercontent.com/72877576/181920434-06663f82-eabb-4cb9-8311-741f0ed4be41.png)
---
I have now renamed `Deutsch.cfg, English.cfg, etc.` to `base.cfg`, but what do I do with the other files, do I need to rename them too, or are there certain symbols  like `-` or `_` that I can't use in a name?

**Comment by dima74** [comment]
Yes, please rename them to any name you choose, so names will be identical in all locale subfolders. Symbols `_` and `-` are allowed

**Comment by Xman1109** [comment]
Okay, All locale files share the same name now (base.cfg and SE-addon.cfg).
I reinstalled the GitHub app and selected More Repair Packs and Atomic Overhaul, I hope it does work now.

**Comment by dima74** [comment]
@Xman1109 sorry for the inconvenience, could you please also rename [`locale/es`](https://github.com/Xman1109/Atomic_Overhaul/tree/a501ebefa795d9df6edca7d40a32e8b2f4ff925e/locale/es) to `locale/es-ES`? And then reinstall the helper for the `Atomic_Overhaul` mod

**Comment by Xman1109** [comment]
Ok, I've done that, and it is now on Crowdin.

Thank you very much for your help!

**Comment by dima74** [comment]
Great, please let me know if you encounter any other problems
