### ISSUE TITLE
Stopped updating translations?

### ISSUE THREAD

**Issue by tburrows13** [dima74/factorio-mods-localization#16]
I see that the last translation update was 22 November and I've made changes to my locale files since then that haven't been updated on crowdin (e.g. https://github.com/tburrows13/PowerOverload/commit/14776b9f2bd17456b3277b70a1d56d404a401dbf and https://github.com/tburrows13/ModuleInserterSimplified/commit/a952c6c4bdea71efef9927665e39bb1f971a8912). Perhaps the updater script has crashed or something?

(I'm not in a rush for any of this to be fixed, if it is indeed a bug, just thought I'd let you know!)

**Comment by dima74** [comment]
Hi! The service is not working now unfortunately, because of technical reasons - it was hosted on Heroku and recently Heroku terminated free plans. So I am now in process of searching free Heroku alternatives and migration

**Comment by tburrows13** [comment]
Ah that’s annoying. If you need a paid plan, I’m happy to contribute :)
This tool is pretty valuable, and straightforward to use!

**Comment by dima74** [comment]
@tburrows13 the helper should work now. Please let me know if you find any problems!

**Comment by tburrows13** [comment]
Thanks very much!
