### ISSUE TITLE
Mod not added to Crowdin

### ISSUE THREAD

**Issue by heinwessels** [dima74/factorio-mods-localization#17]
Hello!

Last week I finally setup some of my mods to (hopefully) be localized through the awesome service you created. However, of the 5 mods I selected only four showed up on the Crowdin website. Specifically, [Better Victory Screen](https://github.com/heinwessels/factorio-better-victory-screen) was not added. 

This could be due to the way I did it. My steps:
1. I added the application to my github account.
2. Selected _only_ Better Victory Screen to be localized. 
3. I while later decided to add the others as well, and went into the settings to add those as well.
4. On Sunday checked the Crowdin website, and only saw the 4 mods I added later, but not the first one.

Could you possibly have a look at it? :)

For now I've removed and re-added the mod repo. Will update here if that fixes it.

---

**Screenshots**

![image](https://github.com/dima74/factorio-mods-localization/assets/39875036/135b8646-ce44-42ac-9128-f123d86647c3)

![image](https://github.com/dima74/factorio-mods-localization/assets/39875036/0d3a2ddc-6006-40bd-b8b1-18cb640a9f3e)

(From 19 Jan 2024)
![image](https://github.com/dima74/factorio-mods-localization/assets/39875036/224a32f3-3d32-4a7c-b2a7-fe0005c527d8)

**Comment by heinwessels** [comment]
Update: Removing and adding the repo did not solve it. Now I uninstalled the app, and reinstalled it. Let's see if that works :)

**Comment by dima74** [comment]
Hi @heinwessels, thanks for using factorio mods localization! Could you please rename `locale/en/en.cfg` and `locale/ru/ru.cfg` to something like `locale.cfg`. Currently we expect files in localization folders to have same name as files in english folder. Thanks!

**Comment by heinwessels** [comment]
Ah, thanks! That sounds like it could be it. I changed it now. If it still gives issues I will let you know.

Thanks for your help! And for this really cool service you're offering.

**Comment by heinwessels** [comment]
The mod is now on the Crowdin site as expected. Thanks for you friendly help! Closting this issue :)

![image](https://github.com/dima74/factorio-mods-localization/assets/39875036/79dd1714-2575-4b64-bffd-ab4311d19ec6)
