### ISSUE TITLE
Specify branch

### ISSUE THREAD

**Issue by KiwiHawk** [dima74/factorio-mods-localization#18]
Is it possible to specify which branch should be used? I would like it to detect locale changes in the dev branch rather than main branch. The PRs that it creates should also target the dev branch.

**Comment by dima74** [comment]
I added this functionality, please change [your `factorio-mods-localization.json`](https://github.com/modded-factorio/SeaBlock/blob/main/factorio-mods-localization.json) config file to the:
```json
{
  "mods": ["SeaBlock"],
  "branch": "dev"
}
```

Please note that the config file should be changed in the **`main`** branch  (not in `dev`).
