### ISSUE TITLE
locale parsing issues

### ISSUE THREAD

**Issue by kirazy** [dima74/factorio-mods-localization#2]
Locale strings that contain the (valid) character ; (semi-colon) are improperly/incompletely parsed into the crowd-in project.

Also when you built the project 8/23/2020, a number of locale strings were enclosed in " " (quotes) that are not present in the translations or source locales, for example:

Source line in locale file:
`reskins-bobs-hydrazine-is-blue=Color the Hydrazine Generator a [color=#7ac1de][font=default-bold]light blue[/font][/color] in relation to the fuel. Otherwise, the hydrazine generator will be colored as the fourth tier of fluid generator.\n\n[color=#9cdcfe]Default:[/color] [color=green]Enabled[/color]`

[Translated line on Crowd in:](https://crowdin.com/translate/factorio-mods-localization/686/en-de#30834)
> Färbe den Hydrazin-Generator [color=#7ac1de][font=default-bold]hell blau[/font][/color], so wie den Treibstoff – andernfalls wird er nach der vierten Stufe der Ölgeneratoren gefärbt.

Line in german locale file as committed by FML:
`reskins-bobs-hydrazine-is-blue="Färbe den Hydrazin-Generator [color=#7ac1de][font=default-bold]hell blau[/font][/color], so wie den Treibstoff – andernfalls wird er nach der vierten Stufe der Ölgeneratoren gefärbt.\n\n[color=#9cdcfe]Standard:[/color] [color=green]Aktiviert[/color]"`

**Comment by dima74** [comment]
@kirazy thanks for reporting! I contacted Crowdin support and they managed to fix second issue (wrapping in quotes) for our Crowdin project. Regarding the first issue, they will give answer on Monday, I will post an update here.

Thanks for using `factorio-mods-localization`!

**Comment by dima74** [comment]
> Locale strings that contain the (valid) character ; (semi-colon) are improperly/incompletely parsed into the crowd-in project.

@kirazy this should be fixed now! Could you please check

**Comment by kirazy** [comment]
Verified working

**Comment by raiguard** [comment]
@dima74 Sorry to gravedig, but I am having a similar issue with the Krastorio 2 Crowdin project in regards to it quoting translations. Do you know what the Crowdin team did to fix it?
