### ISSUE TITLE
Support repos with multiple mods

### ISSUE THREAD

**Issue by Cereal-Sam** [dima74/factorio-mods-localization#4]
Repos that have multiple mods 
( for example https://github.com/Cereal-Sam/Factorio-Mods or https://github.com/OmnissiahZelos/omnimatter )
currently dont work with this app.
Supporting those would be very nice.
Splitting up the mods into their own repo would increase commit timesa lot for us since they are pretty coherent.

Each mod could be detected by looking for the info.json in each folder and using that as base path for the locale folder for example.

**Comment by KiwiHawk** [comment]
+1 for supporting this! I've authorized the GitHub app for Sea Block, Circuit Processing and Landfill Painting and none of them seem to have been added. 

The Sea Block repository contains multiple mods. The other two repositories only contain a single mod each. However their folder structure is nested one extra layer deep. I assume that resolving this issue would make them work too?

https://github.com/KiwiHawk/SeaBlock
https://github.com/KiwiHawk/CircuitProcessing
https://github.com/KiwiHawk/LandfillPainting

**Comment by dima74** [comment]
@Cereal-Sam @KiwiHawk I recently added support for multiple mods in a single repository. To use it please add file `factorio-mods-localization.json` with list of mods to the root of repository. E.g. for https://github.com/Cereal-Sam/Factorio-Mods it will be:
```json
[
    "Mud_WaterWell",
    "expensive_entities"
]
```
Please let me know what you think. Thanks!
