### ISSUE TITLE
Handle file deletions

### ISSUE THREAD

**Issue by dima74** [dima74/factorio-mods-localization#7]
> If files was deleted from source locale, script must erase it from Crowdin source too.

**Comment by kirazy** [comment]
I would also add that if the repository was deleted/removed from the app, script should erase it from Crowdin as well.

**Comment by dima74** [comment]
This is implemented in the following way:
1. Mod author deletes some `locale/en/foo.cfg` file
2. Test [`crowdin_github_matches_english_files.rs`](https://github.com/dima74/factorio-mods-localization/blob/1721c58017683215c43add92b66efd7a62be81b4/tests/crowdin_github_matches_english_files.rs) will catch it and I will remove corresponding `foo.ini` english file on Crowdin
3. On next sync from Crowdin leftover `foo.cfg` localization files in GitHub repository will be deleted
