### ISSUE TITLE
Extended Angels (Kirazy) is a deleted repository that doesn't exist

### ISSUE THREAD

**Issue by kirazy** [dima74/factorio-mods-localization#9]
Just letting you know that I deleted the fork, but the locale files are still on Crowdin.

**Comment by Cereal-Sam** [comment]
Same with OmniLocales (Cereal-Sam) (This can be deleted).
This has been moved to OmniLocales (Omnimods).
The bot seems to not recognise removed/deleted repositories.

**Comment by dima74** [comment]
I deleted those repositories on Crowdin, thanks!
Also implemented automatic checks, so I guess we can close this issue
